import { StyleSheet } from 'react-native';
import { colors } from '../../lib/theme';
export const screenStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#FEFEFF' },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 18,
    padding: 24,
    backgroundColor: 'white',
  },
  page: { width: '100%', maxWidth: 820, gap: 10 },
  header: {
    paddingTop: 20,
    paddingBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  languages: {
    flexDirection: 'row',
    backgroundColor: '#F2F3F7',
    borderWidth: 1,
    borderColor: '#E4E7EF',
    borderRadius: 30,
    padding: 1,
  },
  language: { borderRadius: 30, paddingHorizontal: 18, paddingVertical: 5 },
  disclaimer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
    paddingHorizontal: 20,
    paddingVertical: 6,
    backgroundColor: colors.pale,
    borderRadius: 11,
  },
  payoutPlay: {
    backgroundColor: '#B9E8D9',
    borderRadius: 12,
    width: 54,
    height: 54,
    justifyContent: 'center',
    alignItems: 'center',
  },
  referral: {
    backgroundColor: colors.mint,
    borderRadius: 12,
    paddingHorizontal: 25,
    paddingVertical: 13,
    flexDirection: 'row',
    gap: 25,
    alignItems: 'center',
  },
  copyBox: {
    backgroundColor: 'white',
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#B4DEDF',
    borderRadius: 6,
    paddingLeft: 10,
    overflow: 'hidden',
  },
  copyButton: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderLeftWidth: 1,
    borderColor: '#B4DEDF',
  },
  chat: { backgroundColor: colors.subtle, padding: 7, borderRadius: 30 },
  ad: {
    flexDirection: 'row',
    gap: 15,
    backgroundColor: '#FBFBFE',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#D7DCEB',
    borderRadius: 9,
  },
  footerContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(255,255,255,0.98)',
    alignItems: 'center',
    borderTopWidth: 1,
    borderColor: '#F3F5F8',
  },
  footer: { width: '100%', maxWidth: 820, paddingTop: 7 },
  cta: {
    backgroundColor: colors.teal,
    borderRadius: 9,
    minHeight: 55,
    paddingHorizontal: 12,
    paddingVertical: 8,
    justifyContent: 'center',
    alignItems: 'center',
    boxShadow: '0px 2px 4px rgba(0,100,114,.12)',
  },
  nav: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 8,
    paddingBottom: 2,
    gap: 2,
  },
  navItem: {
    flex: 1,
    minWidth: 0,
    minHeight: 56,
    gap: 2,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  navIcon: {
    width: 46,
    height: 32,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navIconActive: { backgroundColor: colors.pale },
  addCompact: { width: 48, height: 48, borderRadius: 14 },
  add: {
    width: 70,
    height: 54,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.teal,
  },
  toast: {
    position: 'absolute',
    alignSelf: 'center',
    width: '90%',
    maxWidth: 520,
    backgroundColor: '#075D67',
    borderRadius: 12,
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    boxShadow: '0px 6px 24px rgba(0,40,50,.2)',
  },
  summary: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 18,
    backgroundColor: colors.pale,
    borderRadius: 12,
  },
  demoNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#FFF8E8',
    padding: 14,
    borderRadius: 10,
    gap: 12,
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: colors.pale,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
