import { StyleSheet } from 'react-native';
import { colors } from '../../lib/theme';
export const sectionStyles = StyleSheet.create({
  registered: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#EAF6F7',
    borderRadius: 9,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderLeftWidth: 1,
    borderColor: '#B8DFE3',
  },
  chip: { paddingHorizontal: 13, paddingVertical: 5, backgroundColor: '#F4F5F9', borderRadius: 8 },
  progress: { height: 5, borderRadius: 4, backgroundColor: '#D6EBED', overflow: 'hidden' },
  play: {
    height: 57,
    width: 57,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EAF7FB',
  },
  countdown: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.pale,
    borderRadius: 13,
    paddingHorizontal: 32,
    paddingVertical: 13,
    gap: 20,
  },
  dates: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 11,
    padding: 5,
  },
  dateCell: {
    width: '50%',
    minHeight: 88,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
  },
  winner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: '#F6F7FA',
    borderRadius: 13,
    overflow: 'hidden',
  },
  miniPlay: {
    position: 'absolute',
    bottom: 5,
    right: 4,
    width: 31,
    height: 31,
    borderRadius: 20,
    borderWidth: 4,
    borderColor: 'white',
    backgroundColor: colors.teal,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reward: {
    minHeight: 32,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: '#F9FAFC',
  },
});
