import { StyleSheet } from 'react-native';
import { colors, font } from '../../lib/theme';
export const styles = StyleSheet.create({
  text: {
    fontFamily: font.regular,
    fontSize: 15,
    color: colors.ink,
    lineHeight: 22,
  },
  card: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 17,
    padding: 20,
    boxShadow: '0px 1px 5px rgba(20, 38, 73, 0.035)',
  },
  button: {
    minHeight: 46,
    borderRadius: 8,
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: colors.teal,
    justifyContent: 'center',
    alignItems: 'center',
  },
  secondary: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: '#B2DDE1',
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(9,23,48,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  sheet: {
    width: '100%',
    maxWidth: 520,
    maxHeight: '88%',
    backgroundColor: 'white',
    borderRadius: 22,
    overflow: 'hidden',
    boxShadow: '0px 16px 60px rgba(10,30,40,.15)',
  },
  sheetHeader: {
    padding: 24,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderColor: colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  input: {
    borderWidth: 1,
    borderColor: '#DDE3EE',
    backgroundColor: '#FCFDFE',
    borderRadius: 10,
    padding: 14,
    fontSize: 15,
    fontFamily: font.regular,
    color: colors.ink,
    minHeight: 49,
  },
  row: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  error: { backgroundColor: '#FFF1F2', borderRadius: 9, padding: 12 },
});
